### ISSUE TITLE
應該遵循設置的字號大小, 寬度.

### ISSUE THREAD

**Issue by tapeon01** [caolib/typora-onelight-theme#11]
如果在配置中就能改的東西, 卻要去改css, 那感覺不是很糟糕嗎?
1. 應該遵守默認寬度, 就寬度設爲900px
```css
#write {
    width: 900px;
}
```
應該將自號設為 `1rem`, 這樣就可以根據設置調整字號, 大概吧.
