### ISSUE TITLE
表格行列调整组件会被代码块遮挡

### ISSUE THREAD

**Issue by caolib** [caolib/typora-onelight-theme#22]
行数较少的表格使用调整表格功能时，调整面板会被下方的代码块遮挡
![Image](https://github.com/user-attachments/assets/f1ee06f9-756d-4770-b3e5-87dd38b67e54)

**Comment by Pupupuuuu** [comment]
问题解决了：以下是Gemini的问题描述，在最后我添加了代码。


太好了！很高兴问题解决了。

现在我来为您刚刚修改的代码添加详细的注释，并解释我们都做了哪些改动以及为什么这么做。

首先，我将在 `onelight.css` 文件中为 `.ty-table-edit` 规则中的 `z-index: 25;` 添加注释。



注释已经添加完毕。

---

接下来，我为您解释一下我们所做的更改和原因：

**问题描述：**
您遇到的问题是，当表格行数较少时，表格的调整面板（由 `.ty-table-edit` 类控制样式）会被其下方的代码块（由 `.md-fences` 类控制样式）遮挡。

**分析过程：**
1.  **初步检查**：我们查看了 `.ty-table-edit` 和 `.md-fences` 的 CSS 规则。两者最初都没有显式设置 `z-index`（控制元素堆叠顺序的属性）或 `position`（定位类型）。
2.  **代码块的堆叠上下文**：进一步检查发现，代码块（`pre.md-fences...`）的 `::after` 伪元素（用于显示代码语言类型）设置了 `position: absolute;` 和 `z-index: 20;`。这使得代码块的语言提示拥有了比普通流中元素更高的堆叠层级。
3.  **堆叠顺序问题**：由于表格调整面板 `.ty-table-edit` 没有明确的 `z-index`，并且其 `position` 属性也未在主题CSS中指定，它的堆叠顺序可能会低于那个带有 `z-index: 20;` 的代码块语言提示，从而导致被遮挡。

**解决方案的尝试与最终方案：**

*   **第一次尝试**：
    *   **操作**：我们给 `.ty-table-edit` 添加了 `position: relative;` 和 `z-index: 25;`。
    *   **原理**：`position: relative;` (或其他非 `static` 的 `position` 值) 通常是让 `z-index` 生效的前提。`z-index: 25;` 的目的是使其高于代码块语言提示的 `z-index: 20;`。
    *   **结果**：整个调整面板消失了。这通常意味着我们添加的 `position: relative;` 与 Typora 内部对该面板的动态定位方式（可能是 `position: absolute;` 或 `position: fixed;`）发生了冲突。

*   **第二次尝试（最终成功方案）**：
    *   **操作**：我们从 `.ty-table-edit` 中移除了 `position: relative;`，但保留了 `z-index: 25;`。
    *   **CSS 规则变动**：
        ```css
        .ty-table-edit {
            /*
             * 提升表格调整面板的堆叠顺序 (z-index)。
             * 设置一个较高的 z-index 值 (例如 25) 可以确保此面板显示在其他元素之上，
             * 特别是代码块右下角的语言提示 (其 z-index 通常为 20)。
             * 这样可以避免面板被页面上其他具有较低 z-index 或默认堆叠顺序的元素遮挡。
             * 注意：此元素可能由 Typora 动态设置了 'position' 属性 (如 'absolute' 或 'fixed')，
             * 因此在这里仅设置 'z-index' 即可生效。之前尝试添加 'position: relative' 会导致面板消失，
             * 表明它干扰了 Typora 的内部定位机制。
             */
            z-index: 25;
            border-radius: var(--radius-large);
            background-color: var(--mica-bg) !important;
            backdrop-filter: var(--mica-blur);
            border: var(--mica-border);
            box-shadow: var(--box-shadow);
            transition: var(--mica-transition);
        }
        ```
    *   **原理**：
        *   保留 `z-index: 25;` 是为了确保调整面板的堆叠层级高于代码块。
        *   移除 `position: relative;` 是因为我们推断 Typora 可能在显示这个面板时，已经通过 JavaScript 动态地给它设置了 `position: absolute` 或 `position: fixed`。在这种情况下，`z-index` 属性本身就可以生效，不需要我们再画蛇添足地添加 `position: relative`。我们添加的 `position: relative` 反而可能覆盖或干扰了 Typora 的定位逻辑，导致面板无法正确定位而消失。
    *   **结果**：调整面板成功显示，并且位于代码块之上，问题解决。

**总结：**
核心改动是在 `.ty-table-edit` 规则中添加了 `z-index: 25;`。这确保了表格调整面板在Z轴上（即屏幕朝向用户的方向）比其他可能遮挡它的元素（如代码块的语言提示，其 `z-index` 为 `20`）有更高的优先显示权。同时，我们发现不需要（也不能）为这个元素设置 `position: relative;`，因为它可能与 Typora 的内部工作方式冲突。

希望这个解释对您有所帮助！

[onelight.zip](https://github.com/user-attachments/files/20321044/onelight.zip)
