### ISSUE TITLE
未显示代码块右下角添加语言类型显示

### ISSUE THREAD

**Issue by tang-zack** [caolib/typora-onelight-theme#7]
<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/1fed0355-b0dd-4471-ac84-f0e680b0c9fa" />  最新的主题没有显示【 代码块右下角添加语言类型显示】 

<img width="1764" alt="Image" src="https://github.com/user-attachments/assets/2d1cf3ea-9926-4487-a074-e0657aa5d24f" />

**Comment by caolib** [comment]
### 我这里是能正常显示的，可能是操作系统的原因，我没有Mac设备所以我也很难找到问题

一个可能的解决方案：在 `onelight.css`文件中搜索找到这部分代码，然后试着将类选择器(第一行)修改得模糊一点

```css
/* 代码框右下角的语言类型显示 */
pre.md-fences.md-end-block.md-fences-with-lineno.ty-contain-cm.modeLoaded::after {
    content: attr(lang);
    position: absolute;
    right: 0;
    bottom: 0;
    color: #e0e0e0;
    padding: 2px 5px;
    border-radius: 3px;
    z-index: 100;
}
```

比如修改为

```css
pre.md-fences.md-end-block::after {
  // 其他代码不变...
}
```

或者再模糊一点，改完记得保存后然后重启typora

```css
pre.md-fences::after {
  // 其他代码不变...
}
```

如果能提供一下控制台的相关信息给我就更好了

![Image](https://github.com/user-attachments/assets/4f73637f-45e9-4122-a404-26f4740424dd)
